spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.126.128:3306/rrvideo_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: rrvideo-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 10000

# 配置详情请看: rrvideo-ware中的注释
