spring:
  # 数据库源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.126.128:3306/rrvideo_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 服务名称
  application:
    name: rrvideo-ware
  # nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# mybatis-plus配置
mybatis-plus:
  # 搜索当前项目目录 + 依赖的Jar包的目录, 底下的resources/mapper下任意文件夹下的所有.xml文件
  # mapper-locations: classpath*:/mapper/**/*.xml

  # 搜索当前项目目录, 底下的resources/mapper下任意文件夹下的所有.xml文件
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

# 端口配置
server:
  port: 11000